import { AnalysisResult, DemoScenario } from '../types/analysis';

/**
 * HARIS (حارس) — Mock Demo Scenarios & Baseline Mock Results
 * NOTE: This file is strictly for Phase 2 UI design and demo demonstration.
 * No real AI processing is performed here.
 */

export const mockDefaultResult: AnalysisResult = {
  isMockData: true,
  inputMode: 'text',
  inputPreview: 'عزيزي العميل، تم إيقاف بطاقتك الائتمانية مؤقتاً لأسباب أمنية. يرجى تحديث بياناتك فوراً خلال ساعتين لتجنب الغرامة عبر الرابط: https://alrajhi-secure-login.xyz/verify وإدخال رمز التحقق المرسل لهاتفك.',
  riskScore: 91,
  riskLevel: 'high',
  scamType: 'انتحال جهة مالية ومصرفية',
  summary: 'تم رصد مؤشرات احتيال هندسة اجتماعية عالية الخطورة؛ الرسالة تدعي كذباً تجميد الحساب المصرفي وتمارس ضغطاً زمنياً شديداً لدفعك لإدخال بيانات اعتمادك ورمز التحقق عبر نطاق خبيث.',
  scamDna: [
    {
      id: 'urgency',
      nameAr: 'الاستعجال وضغط الوقت',
      nameEn: 'Urgency & Pressure',
      detected: true,
      severity: 'high',
      detail: 'استخدام عبارات التهديد بإيقاف الحساب خلال ساعتين لإرباك الضحية ومنعها من التفكير العقلاني.',
    },
    {
      id: 'impersonation',
      nameAr: 'انتحال الهوية',
      nameEn: 'Identity Impersonation',
      detected: true,
      severity: 'high',
      detail: 'انتحال صفة مصرف الراجحي دون استخدام البريد أو القنوات المصرفية الرسمية المعتمدة.',
    },
    {
      id: 'credential_request',
      nameAr: 'طلب معلومات حساسة',
      nameEn: 'Credential Harvesting',
      detected: true,
      severity: 'high',
      detail: 'محاولة الاستيلاء على أرقام البطاقة وكلمة المرور من خلال صفحة تصيد ملغومة.',
    },
    {
      id: 'otp_request',
      nameAr: 'طلب رمز التحقق (OTP)',
      nameEn: 'OTP Interception',
      detected: true,
      severity: 'high',
      detail: 'طلب إدخال رمز التحقق لمرة واحدة في الصفحة للسيطرة الكاملة على الحساب البنكي.',
    },
    {
      id: 'suspicious_url',
      nameAr: 'رابط احتيالي مشبوه',
      nameEn: 'Suspicious Domain',
      detected: true,
      severity: 'high',
      detail: 'النطاق المستخدم (.xyz) مسجل حديثاً ويحاكي اسم البنك لخداع المستخدم، ولا يرتبط بالنطاق الرسمي للبنك.',
    },
    {
      id: 'financial_lure',
      nameAr: 'حافز مالي / ادعاء مكافأة',
      nameEn: 'Financial Lure',
      detected: false,
      severity: 'low',
      detail: 'لم يُرصد وعد بمكافأة؛ تم استخدام أسلوب الترهيب والتهديد المالي بدلاً من الإغراء.',
    },
  ],
  evidence: [
    {
      id: 'ev-1',
      title: 'تهديد زمني وتخويف من غرامة مالية',
      description: 'الرسالة تدعي إيقاف البطاقة خلال ساعتين وفرض غرامة، وهي أساليب لا تستخدمها البنوك المرخصة إطلاقاً.',
      severity: 'high',
      source: 'linguistic',
    },
    {
      id: 'ev-2',
      title: 'نطاق تصيد منتحل للعلامة التجارية',
      description: 'الرابط `alrajhi-secure-login.xyz` يستخدم نطاقاً غير مصرفي (.xyz) ويهدف لاصطياد الضحايا.',
      severity: 'high',
      source: 'technical',
    },
    {
      id: 'ev-3',
      title: 'محاولة استدراج رمز التحقق لمرة واحدة (OTP)',
      description: 'البنوك تنص دائماً على أن موظفيها لن يطلبوا رمز التحقق الخاص بك تحت أي ظرف.',
      severity: 'high',
      source: 'behavioral',
    },
  ],
  actionableAdvice: [
    'لا تضغط على الرابط نهائياً ولا تدخل أي معلومة في الصفحة.',
    'لا تشارك رمز التحقق (OTP) المرسل على هاتفك مع أي شخص أو موقع غير موثوق.',
    'تواصل فوراً مع مصرفك عبر الرقم الرسمي المطبوع خلف بطاقتك البنكية.',
    'أبلغ عن الرسالة المشبوهة للجهات الأمنية وقنوات مكافحة الاحتيال الرسمية (مثل 330330 في السعودية).',
  ],
  uncertainties: [
    'لم يتم تتبع الرابط أو زيارته من خوادمنا تجنباً لتنشيط البرمجيات الخبيثة وتأكيداً لسياسة الأمان السلبي.',
    'التقييم مستند إلى المؤشرات الرقمية والهندسية المستخرجة ولا يمثل حكماً قانونياً قاطعاً.',
  ],
  analyzedAt: 'منذ قليل',
};

export const demoScenarios: DemoScenario[] = [
  {
    id: 'banking-scam',
    title: 'احتيال بنكي صريح',
    badge: 'احتيال مالي',
    mode: 'text',
    description: 'رسالة نصية تزعم إيقاف البطاقة الائتمانية مع رابط وهمي يطلب OTP.',
    content: 'عزيزي العميل، تم إيقاف بطاقتك الائتمانية مؤقتاً لأسباب أمنية. يرجى تحديث بياناتك فوراً خلال ساعتين لتجنب الغرامة عبر الرابط: https://alrajhi-secure-login.xyz/verify وإدخال رمز التحقق المرسل لهاتفك.',
    mockResult: mockDefaultResult,
  },
  {
    id: 'complex-arabic-scam',
    title: 'لهجة عربية معقدة ومختلطة',
    badge: 'عربيزي وتمويه',
    mode: 'text',
    description: 'رسالة تجمع بين اللهجة العامية، أخطاء إملائية مقصودة، عربيزي، ورموز تعبيرية.',
    content: 'مبروووك يا غالي 🎉 7سابك كسب معنا قسيمة شرائية بـ 3000 ريال 💸 يرجى confirm بياناتك اليوم ولا الفرصة بتروح عليك: http://stc-rewards.top/claim2024?id=99281',
    mockResult: {
      ...mockDefaultResult,
      inputPreview: 'مبروووك يا غالي 🎉 7سابك كسب معنا قسيمة شرائية بـ 3000 ريال 💸 يرجى confirm بياناتك اليوم ولا الفرصة بتروح عليك: http://stc-rewards.top/claim2024?id=99281',
      riskScore: 88,
      riskLevel: 'high',
      scamType: 'جائزة وهمية وإغراء مالي',
      summary: 'تحليل النص أظهر محاولة واضحة للالتفاف على فلاتر الرسائل عبر خلط العامية بالإنجليزية والعربيزي (7سابك)، مع إغراء مالي وهمي ورابط خارجي غير آمن.',
      scamDna: [
        {
          id: 'financial_lure',
          nameAr: 'حافز مالي / جائزة خيالية',
          nameEn: 'Financial Lure',
          detected: true,
          severity: 'high',
          detail: 'الوعد بمكافأة نقدية بقيمة 3000 ريال لاستدراج الضحية.',
        },
        {
          id: 'impersonation',
          nameAr: 'انتحال علامة تجارية',
          nameEn: 'Brand Impersonation',
          detected: true,
          severity: 'high',
          detail: 'استغلال اسم شركة الاتصالات في النطاق الفرعي لخلق ثقة زائفة.',
        },
        {
          id: 'urgency',
          nameAr: 'استعجال مصطنع',
          nameEn: 'Urgency Pressure',
          detected: true,
          severity: 'medium',
          detail: 'عبارة "ولا الفرصة بتروح عليك" لتسريع قرار الضحية.',
        },
        {
          id: 'suspicious_url',
          nameAr: 'رابط TLD مشبوه (.top)',
          nameEn: 'Suspicious TLD',
          detected: true,
          severity: 'high',
          detail: 'استخدام نطاق علوي تجاري رخيص (.top) غير مشهور للشركات الموثوقة.',
        },
        {
          id: 'credential_request',
          nameAr: 'طلب معلومات حساسة',
          nameEn: 'Data Harvesting',
          detected: true,
          severity: 'medium',
          detail: 'طلب تأكيد البيانات الشخصية لاستلام الجائزة المزعومة.',
        },
      ],
      evidence: [
        {
          id: 'ev-c1',
          title: 'محاولة تمويه لغوي وتجاوز الرقابة',
          description: 'استخدام كتابة مشوهة للأحرف (7سابك) لتفادي أنظمة مكافحة الرسائل الاحتيالية لشركات الاتصالات.',
          severity: 'high',
          source: 'linguistic',
        },
        {
          id: 'ev-c2',
          title: 'رابط تصيد خارجي غير مشفر (HTTP)',
          description: 'الرابط يستخدم بروتوكول HTTP غير المشفر مع نطاق .top المصنف دولياً ضمن أعلى النطاقات تسجيلاً لحملات التصيد.',
          severity: 'high',
          source: 'technical',
        },
      ],
      actionableAdvice: [
        'تجاهل هذه الرسائل تماماً؛ الشركات الكبرى لا توزع جوائز نقدية عشوائية عبر روابط.',
        'لا تفتح الرابط لأن النطاقات غير المشفرة قد تستغل ثغرات بالمتصفح.',
        'احظر الرقم وقم بالإبلاغ عنه فوراً.',
      ],
    },
  },
  {
    id: 'delivery-scam',
    title: 'احتيال طرود وشحن',
    badge: 'خدمات لوجستية',
    mode: 'screenshot',
    description: 'لقطة شاشة لرسالة احتيال بريد وتوصيل تزعم الحاجة لدفع رسوم شحن رمزية.',
    content: '[لقطة شاشة]: شحنتك رقم SA-88391 معلقة في المستودع الرئيسي بسبب نقص رسوم الجمارك (9.50 ر.س). يرجى السداد خلال 24 ساعة لاستلام الشحنة: https://spl-saudi-track.live/pay',
    mockResult: {
      ...mockDefaultResult,
      inputMode: 'screenshot',
      inputPreview: '[لقطة شاشة]: رسالة SMS تدعي تعليق شحنة بريدية وتطلب تسوية رسوم شحن 9.50 ريال عبر رابط مشبوه.',
      riskScore: 84,
      riskLevel: 'high',
      scamType: 'احتيال شحن وتوصيل (رسوم وهمية)',
      summary: 'أسلوب تصيد شهير يعتمد على طلب مبالغ مالية زهيدة (9.50 ريال) لتقليل ارتياب الضحية، والهدف الحقيقي هو سرقة بيانات بطاقة الدفع (CVV ورقم البطاقة).',
      scamDna: [
        {
          id: 'impersonation',
          nameAr: 'انتحال هوية البريد والشحن',
          nameEn: 'Postal Impersonation',
          detected: true,
          severity: 'high',
          detail: 'انتحال هوية البريد السعودي (سبل) برقم تتبع عشوائي زائف.',
        },
        {
          id: 'credential_request',
          nameAr: 'استدراج بيانات الدفع والبطاقة',
          nameEn: 'Payment Data Harvesting',
          detected: true,
          severity: 'high',
          detail: 'محاولة توجيه المستخدم لصفحة دفع وهمية لسرقة بيانات البطاقة البنكية.',
        },
        {
          id: 'urgency',
          nameAr: 'ضغط الوقت والتعليق',
          nameEn: 'Urgency & Delay Threat',
          detected: true,
          severity: 'medium',
          detail: 'الادعاء بأن الشحنة ستُعاد إلى المصدر خلال 24 ساعة إن لم يتم السداد.',
        },
        {
          id: 'suspicious_url',
          nameAr: 'نطاق تتبع مزيف (.live)',
          nameEn: 'Fake Tracking Domain',
          detected: true,
          severity: 'high',
          detail: 'النطاق `spl-saudi-track.live` ليس له أي صلة بالبوابة الرسمية `splonline.com.sa`.',
        },
      ],
      evidence: [
        {
          id: 'ev-d1',
          title: 'طلب رسوم رمزية للإيقاع بالضحية',
          description: 'تحديد مبالغ قليلة (أقل من 10 ريالات) هو نمط احتيالي معروف لتشجيع الضحية على إدخال البطاقة دون تردد.',
          severity: 'high',
          source: 'behavioral',
        },
        {
          id: 'ev-d2',
          title: 'نطاق منتحل مسجل حديثاً',
          description: 'النطاق لا ينتهي بالامتداد الحكومي الرسمي للمملكة (.gov.sa) ولا النطاق التجاري المعتمد لشركة البريد.',
          severity: 'high',
          source: 'technical',
        },
      ],
      actionableAdvice: [
        'لا تدخل أي بيانات دفع أو بطاقة بنكية في هذا الرابط.',
        'افتح التطبيق الرسمي لشركة التوصيل أو الموقع المعتمد وتحقق من وجود أي شحنة مسجلة برقم هويتك.',
        'الشركات المعتمدة لا تطلب بطاقات ائتمانية عبر نطاقات غير رسمية مجهولة.',
      ],
    },
  },
];
